/* KATO – main.js : data → reusable components → behaviours */
(() => {
'use strict';
const $ = (s, r = document) => r.querySelector(s), $$ = (s, r = document) => [...r.querySelectorAll(s)];
const IMG = 'assets/images/', PAGE = document.body.dataset.page || 'home';

/* ---------- icons (inline SVG, no library) ---------- */
const P = {
 check:'<polyline points="20 6 9 17 4 12"/>',cc:'<path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/><polyline points="22 4 12 14.01 9 11.01"/>',
 phone:'<path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72c.13.96.36 1.9.7 2.81a2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45c.91.34 1.85.57 2.81.7A2 2 0 0 1 22 16.92z"/>',
 mail:'<path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/>',
 pin:'<path d="M21 10c0 7-9 13-9 13s-9-6-9-13a9 9 0 0 1 18 0z"/><circle cx="12" cy="10" r="3"/>',clock:'<circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/>',
 wa:'<path d="M21 11.5a8.38 8.38 0 0 1-.9 3.8 8.5 8.5 0 0 1-7.6 4.7 8.38 8.38 0 0 1-3.8-.9L3 21l1.9-5.7a8.38 8.38 0 0 1-.9-3.8 8.5 8.5 0 0 1 4.7-7.6 8.38 8.38 0 0 1 3.8-.9h.5a8.48 8.48 0 0 1 8 8v.5z"/>',
 fb:'<path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"/>',zap:'<polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/>',
 cpu:'<rect x="4" y="4" width="16" height="16" rx="2"/><rect x="9" y="9" width="6" height="6"/><path d="M9 1v3M15 1v3M9 20v3M15 20v3M20 9h3M20 14h3M1 9h3M1 14h3"/>',
 wind:'<path d="M9.59 4.59A2 2 0 1 1 11 8H2m10.59 11.41A2 2 0 1 0 14 16H2m15.73-8.27A2.5 2.5 0 1 1 19.5 12H2"/>',drop:'<path d="M12 2.69l5.66 5.66a8 8 0 1 1-11.31 0z"/>',
 tool:'<path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/>',
 home:'<path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/>',shield:'<path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/>',
 plus:'<line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/>',arrow:'<line x1="19" y1="12" x2="5" y2="12"/><polyline points="12 19 5 12 12 5"/>',up:'<polyline points="18 15 12 9 6 15"/>',
 eye:'<circle cx="12" cy="12" r="3"/><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/>',eye2:'<path d="M15 3h6v6M10 14L21 3M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/>',
 target:'<circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/>',file:'<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/>',
 users:'<path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 0 0-3-3.87"/><path d="M16 3.13a4 4 0 0 1 0 7.75"/>',
 award:'<circle cx="12" cy="8" r="7"/><polyline points="8.21 13.89 7 23 12 20 17 23 15.79 13.88"/>',trend:'<polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/><polyline points="17 6 23 6 23 12"/>'};
const ic = n => `<svg class="i" viewBox="0 0 24 24" aria-hidden="true">${P[n]}</svg>`;

/* ---------- KATO data ---------- */
const C = {phone:'01028644675', phone2:'01124271997', mail:'katto100100@gmail.com', wa:'https://wa.me/201028644675', fb:'https://www.facebook.com/profile.php?id=61578658141960', addr:'السويس – السلام 1 – شارع عثمان، بجوار مسجد سعد ابن أبي وقاص'};
const SVC = [
 {t:'كهرباء وكنترول صناعي',s:'لوحات، تأسيس، شبكات، حماية',ic:'zap',img:'p-electrical',d:'حلول كهربائية صناعية متكاملة من تأسيس اللوحات إلى ربط خطوط الإنتاج بأنظمة الكنترول، بإدارة فريق متخصص وتقارير موثقة.',
  g:[['لوحات الكنترول والباور',['صيانة وتركيب لوحات الكنترول والباور','إدارة غرف الجهد المنخفض','متابعة الأحمال والحمايات','تنظيم وتطوير اللوحات','ربط خطوط الإنتاج بأنظمة الكنترول','صيانة الأعطال وتقليل تكرارها']],['التأسيس والتشطيب الكهربائي',['تخطيط وتصميم الشبكة الكهربائية','تمديد الكابلات وكابل تراي','تركيب اللوحات الرئيسية والفرعية','أنظمة التأريض الصناعي','خدمة طوارئ 24/7']]],sec:['مصانع الأغذية','مصانع الأدوية','البلاستيك','الكيماويات','المخازن','المباني الإدارية']},
 {t:'أنظمة PLC والتحكم الآلي',s:'برمجة، HMI، SCADA، VFD',ic:'cpu',img:'p-cctv',d:'برمجة وتركيب وصيانة أنظمة PLC من كبرى العلامات (Siemens, Delta, Mitsubishi) مع شاشات HMI وأنظمة SCADA وVFD.',
  g:[['تركيب وبرمجة',['برمجة وتركيب PLC (Siemens, Delta, Mitsubishi)','شاشات HMI وأنظمة SCADA','Variable Frequency Drives (VFD)','أنظمة الحساسات والسنسورات','ربط الأنظمة بأنظمة المراقبة']],['صيانة وتحسين الأداء',['صيانة وتعديل البرامج','تحسين أداء خطوط الإنتاج','استكشاف وإصلاح الأعطال','تدريب الكوادر الفنية','تقارير أداء شهرية']]],sec:['مصانع الإنتاج','خطوط التجميع','الصناعات الغذائية','الأدوية','البلاستيك']},
 {t:'التكييف الصناعي',s:'تركيب، صيانة، شحن فريون',ic:'wind',img:'p-ac',d:'تركيب وصيانة أنظمة التكييف الصناعي بمختلف أنواعها — من وحدات منفصلة إلى أنظمة مركزية للمصانع والمرافق الكبيرة.',
  g:[['تركيب وصيانة',['تركيب وحدات التكييف الصناعي','صيانة دورية شاملة','تنظيف وغسيل الوحدات','شحن الفريون وإصلاح التسريبات','رفع كفاءة التشغيل في بيئات العمل المستمر']],['تشخيص وحلول',['فحص أعطال التبريد والتسخين','قياس كفاءة الطاقة','استبدال الضواغط والمكونات','ضبط أنظمة التحكم في الحرارة','توريد قطع غيار أصلية']]],sec:['المصانع','المخازن','المباني الإدارية','المراكز التجارية','المراكز اللوجستية']},
 {t:'الفلاتر وأنظمة المياه',s:'فلاتر، RO، محطات تحلية',ic:'drop',img:'p-lifts',d:'حلول متكاملة لأنظمة المياه الصناعية: فلاتر معالجة، أنظمة RO، محطات تحلية، ومتابعة جودة المياه بشكل دوري.',
  g:[['تركيب وصيانة الفلاتر',['تركيب وصيانة فلاتر المياه الصناعية','متابعة جودة المياه','استبدال المكونات الدورية','أنظمة RO وتحلية المياه','فلاتر معالجة مياه العمليات']],['تشغيل وتحسين',['ضبط معدلات التدفق','تحسين كفاءة الترشيح','تقارير دورية لجودة المياه','صيانة المضخات والضواغط','استشارات فنية لترقية المنظومة']]],sec:['الأغذية والمشروبات','الأدوية','الكيماويات','المستشفيات','المصانع بشكل عام']},
 {t:'السباكة الصناعية',s:'شبكات، مضخات، PPR وPVC',ic:'tool',img:'p-install',d:'تأسيس وصيانة شبكات المياه والصرف داخل المصانع بمواد عالية الجودة (PPR, PVC) ومعايير تركيب احترافية.',
  g:[['شبكات وصيانة',['تأسيس شبكات المياه داخل المصانع','صيانة الأعطال والتسريبات','إدارة المرافق المرتبطة بالمياه','تمديد مواسير PPR وPVC','تركيب وصيانة مضخات المياه']],['حلول متقدمة',['تصميم شبكات المياه والصرف','تركيب خزانات المياه','محطات الرفع','فحص الشبكات بكاميرات حرارية','صيانة دورية وقائية']]],sec:['المصانع','المخازن','المباني الإدارية','المجمعات التجارية','المنشآت الكبيرة']},
 {t:'المقاولات والتشطيبات',s:'تجهيز مواقع، دهانات، تشطيبات',ic:'home',img:'p-safety',d:'تجهيز مواقع إنتاج جديدة، أعمال التشطيبات، والدهانات الصناعية بمعايير السلامة والجودة المؤسسية.',
  g:[['تجهيز المواقع',['أعمال كهرباء من التأسيس للتشغيل','تجهيز مواقع ومحلات','تشطيبات داخلية','دهانات ونقاشة صناعية','تجهيز مواقع إنتاج جديدة','أرضيات إيبوكسي صناعية']],['مقاولات متخصصة',['بناء غرف ومكاتب إدارية','هياكل معدنية وحواجز سلامة','أنظمة تهوية وعوادم','تنسيقات مدنية وكهربائية','إدارة مشروع كاملة']]],sec:['المصانع الجديدة','التوسعات','المخازن','المحلات التجارية','المباني الإدارية']}];
const IND = [['مصانع الأغذية','صيانة تتوافق مع معايير HACCP وسلامة الغذاء','p-maint'],['مصانع الأدوية','بيئات نظيفة وامتثال GMP كامل','p-lifts'],['مصانع البلاستيك','صيانة ماكينات البثق والحقن والقولبة','p-install'],['مصانع الكيماويات','صيانة في بيئات حساسة مع بروتوكولات سلامة صارمة','p-safety'],['المصانع المعدنية','صيانة مكثفة لخطوط الإنتاج المعدني','p-emerg'],['المخازن واللوجستيات','صيانة أنظمة التخزين والرافعات والإضاءة','p-cctv'],['المباني الإدارية','تشغيل وصيانة المرافق الإدارية بالكامل','p-electrical'],['المراكز التجارية','صيانة HVAC وكهرباء وأنظمة السلامة','p-ac']];
const WHY = [['استجابة سريعة','فرق جاهزة للطوارئ على مدار الساعة. نوصل خلال ساعات من البلاغ ونبدأ التشخيص الفوري.'],['صيانة وقائية حقيقية','جداول زمنية واضحة لكل بند صيانة، تنفيذ منظم، وتقارير موثقة قبل وبعد العمل.'],['تقارير فنية احترافية','تقارير دورية تساعد الإدارة على اتخاذ القرار: حالة المعدات، المخاطر، التوصيات، وخطة التحسين.'],['كوادر متخصصة','فنيون معتمدون لكل تخصص: كهرباء، تحكم آلي، تكييف، سباكة، ميكانيكا. تدريب مستمر.'],['إدارة عقود واضحة','نطاق خدمة مفصل، استجابة مضمونة، شفافية كاملة في التسعير. لا مفاجآت.'],['متابعة مستمرة','متابعة دورية لما بعد التنفيذ، قياس مؤشرات الأداء، وتطوير مستمر للخطة.']];
const STEPS = [['المعاينة','معاينة ميدانية سريعة وتحديد نقاط المخاطر'],['الدراسة الفنية','تحليل الحالة الراهنة وتحديد الأولويات'],['العرض الفني والمالي','عرض واضح بنطاق خدمة مفصل وتسعير شفاف'],['التنفيذ','فريق متخصص بأعلى معايير الجودة والسلامة'],['المتابعة','متابعة دورية لما بعد التنفيذ وقياس الأداء'],['التقارير الدورية','تقارير فنية دورية لدعم القرار الإداري']];
const CATS = {electrical:'كهرباء',automation:'تحكم آلي',hvac:'تكييف',civil:'مقاولات'};
const PRJ = [
 {t:'ترقية نظام PLC لخط الإنتاج',c:'automation',sec:'قطاع الأغذية',loc:'مصنع أغذية – القاهرة · 2025',img:'p-cctv',sz:'t1',d:'استبدال نظام تحكم قديم بنظام Siemens S7-1500 مع شاشة HMI جديدة وتقليل زمن التوقفات بنسبة كبيرة.',r:'−42%',rl:'نسبة توقفات الخط شهريًا'},
 {t:'عقد صيانة شامل لخطوط البثق',c:'electrical',sec:'قطاع البلاستيك',loc:'مصنع بلاستيك – العاشر من رمضان · 2024',img:'p-maint',sz:'t3',d:'عقد صيانة وقائية شهرية لـ 6 خطوط بثق، يشمل تنظيف، معايرة، تبديل قطع غيار، وتقارير شهرية للإدارة.',r:'+28%',rl:'ارتفاع كفاءة الخط الإنتاجي'},
 {t:'تشغيل وصيانة مرافق مستودع 12,000 م²',c:'civil',sec:'قطاع لوجستي',loc:'مركز لوجستي – السويس · 2025',img:'p-lifts',sz:'t2',d:'تشغيل كامل لأنظمة الكهرباء، الإضاءة، HVAC، وأنظمة السلامة لفريق مقيم 3 فنيين على مدار اليوم.',r:'0',rl:'حوادث سلامة خلال 18 شهرًا'},
 {t:'لوحات كهربائية صناعية',c:'electrical',img:'p-electrical',sz:'t2',d:'تركيب وتنظيم لوحات باور وكنترول'},
 {t:'أنظمة PLC والكنترول',c:'automation',img:'p-emerg',sz:'t3',d:'برمجة Siemens S7-1500 وشاشات HMI'},
 {t:'تكييف صناعي',c:'hvac',img:'p-ac',sz:'t1'},{t:'صيانة كهربائية شاملة',c:'electrical',img:'p-install',sz:'t3'},
 {t:'تجهيز مواقع إنتاج',c:'civil',img:'p-safety',sz:'t2'},{t:'تركيب HVAC',c:'hvac',img:'p-ac',sz:'t3'},{t:'غرف تحكم صناعية',c:'automation',img:'p-cctv',sz:'t2'}];
const TES = [['فريق كاتو التزم بخطة الصيانة بدقة، والتقارير الشهرية ساعدتنا نتحكم في تكاليف التشغيل بشكل ملحوظ. أنصح بالتعامل معهم لأي مصنع.','م. أحمد فؤاد','مدير مصنع – قطاع البلاستيك'],['استجابة سريعة جدًا للطوارئ. مرة واحدة اتصلنا في الساعة 3 الفجر وكان عندنا فني في الموقع خلال ساعتين. ده غير معتاد في السوق.','م. سامي رضوان','مدير صيانة – قطاع الأغذية'],['التعامل مع كاتو منظم من البداية للنهاية. من المعاينة الأولى للتقرير النهائي، كل حاجة موثقة واحترافية. ده اللي كنا محتاجينه فعلاً.','أ. خالد مصطفي','مالك مصنع – قطاع الكيماويات']];
const FAQ = [['ما الخدمات التي تقدمها الشركة؟','نقدم ست خدمات متكاملة: كهرباء وكنترول صناعي، أنظمة PLC والتحكم الآلي، التكييف الصناعي، الفلاتر وأنظمة المياه، السباكة الصناعية، والمقاولات والتشطيبات.'],['ما القطاعات التي تخدمونها؟','مصانع الأغذية والأدوية والبلاستيك والكيماويات والمعادن، والمخازن واللوجستيات، والمباني الإدارية، والمراكز التجارية.'],['هل توفرون خدمات الصيانة؟','نعم. نقدم صيانة وقائية بجداول واضحة وتقارير موثقة، مع استجابة طوارئ على مدار الساعة 24/7 وفرق جاهزة للوصول خلال ساعات من البلاغ.'],['هل يمكن طلب معاينة للموقع؟','بالتأكيد. المعاينة الميدانية مجانية، وبعد إرسال طلبك سيتواصل معك فريقنا خلال 24 ساعة لتحديد موعد المعاينة.'],['كيف يمكن الحصول على عرض سعر؟','بعد المعاينة والدراسة الفنية نقدم عرضًا فنيًا وماليًا بنطاق خدمة مفصل وتسعير شفاف. يمكنك أيضًا طلبه عبر النموذج أو واتساب.'],['هل تقدمون عقود صيانة؟','نعم، لدينا ثلاثة أنظمة تعاقد: زيارات تفقدية، صيانة شهرية، وتشغيل كامل بفريق مقيم. تُحدد التفاصيل النهائية بعد المعاينة الفنية.']];
const PLANS = [['مرنة','زيارات تفقدية','جولات منتظمة للكشف المبكر على المشاكل قبل ما تتحول لأعطال. مناسبة للمواقع اللي عندها فريق داخلي.',['تفقد + تقرير','48 ساعة','2-4 / شهر','بعد كل زيارة','هاتف'],'طلب عرض سعر','* السعر حسب حجم الموقع'],['موصى به','صيانة شهرية','صيانة وقائية شهرية تضمن استقرار التشغيل وتقلل التوقف. مناسبة لمعظم المصانع متوسطة الحجم.',['وقائية شاملة','12 ساعة','8-12 / شهر','شهرية تفصيلية','هاتف + طوارئ'],'احجز معاينة','✦ خصومات على قطع الغيار'],['مؤسسي','تشغيل كامل','إدارة وتشغيل متكامل لجميع مرافق الموقع بفريق مخصص مقيم. للمواقع الكبيرة والمتعددة.',['تشغيل متكامل','فوري 24/7','فريق مقيم','شهرية + سنوية','فني مقيم + طوارئ'],'تواصل معنا','* يُحدد بعد المعاينة والتقييم الشامل']];
const ROWS = ['نطاق الخدمة','زمن الاستجابة','عدد الزيارات','التقارير','الدعم الفني'];
const KPI = [['نسبة نجاح الأعمال','98%','+3% عن العام السابق','award'],['معدل الالتزام بالمواعيد','97%','+5% عن العام السابق','clock'],['متوسط زمن الاستجابة','3.5 ساعة','−1.2 ساعة عن العام السابق','zap'],['رضا العملاء','96%','+4% عن العام السابق','users']];
const REP = [['حالة اللوحات','تقرير شامل بحالة جميع اللوحات الكهربائية وأنظمة الكنترول في الموقع.','file'],['نقاط الخطر','تحديد دقيق للمناطق التي تحتاج إلى تدخل فوري أو وقائي مع تصنيف الأولوية.','shield'],['توصيات فنية','توصيات مفصلة لتحسين الأداء وتقليل المخاطر، مع تبرير فني وتقدير تكلفة.','target'],['خطة تحسين','خطة زمنية واضحة لتطوير أنظمة التشغيل على المدى القصير والمتوسط.','trend']];
const TL = [['2020','التأسيس','بداية الفكرة وتنفيذ أول عقود الصيانة'],['2021','التوسع الأول','دخول قطاعات الأغذية والبلاستيك'],['2022','قسم التحكم الآلي','إضافة PLC وSCADA والقياسات الصناعية'],['2024','عقود تشغيل كاملة','توقيع أول عقد تشغيل متكامل لمصنع'],['2026','المرحلة الحالية','+500 موقع، +5 سنوات خبرة ميدانية']];
const STD = ['OSHA Safety','ISO 9001:2015','NFC Fire Code','IEC 60364','ISO 14001'];

/* ---------- components (each returns markup) ---------- */
const head = (e, h, l, c) => `<div class="sec-head ${c || ''}"><div><span class="eyebrow">${e}</span><h2>${h}</h2>${l ? `<p class="lead">${l}</p>` : ''}</div></div>`;
const R = {
stats: () => `<section class="stats" aria-label="أرقام الشركة"><div class="container"><div class="stats-grid">${[['500','+','عميل راضي خدمناه'],['24/7','','استجابة طوارئ'],['98','%','نسبة الالتزام بالمواعيد'],['5','+','سنوات خبرة ميدانية']].map(([n, s, l], i) => `<div class="stat rv d${i}"><b>${/^\d+$/.test(n) ? `<span data-count="${n}">0</span>` : n}${s ? `<sup>${s}</sup>` : ''}</b><span>${l}</span></div>`).join('')}</div></div></section>`,

services: () => `<section class="section" id="services"><div class="container">${head('خدماتنا', 'حلول صيانة وتشغيل متكاملة للمصانع', 'من الكهرباء والتحكم الآلي إلى السباكة والتكييف والمقاولات — فريق متخصص لكل تخصص تحت إدارة موحدة.')}<div class="svc-grid">${SVC.map((s, i) => `<article class="svc rv d${i % 3}"><div class="ph"><img loading="lazy" src="${IMG + s.img}.jpg" alt="${s.t}"><span class="ico">${ic(s.ic)}</span><span class="num">0${i + 1}</span></div><div class="bd"><h3>${s.t}</h3><p class="sh">${s.s}</p><ul>${s.g[0][1].slice(0, 3).map(x => `<li>${ic('check')}${x}</li>`).join('')}</ul><a class="link" href="services.html#s${i + 1}">التفاصيل ${ic('arrow')}</a></div></article>`).join('')}</div></div></section>`,

featured: () => `<section class="section soft"><div class="container feat"><div class="img rv"><img loading="lazy" src="${IMG}p-lifts.jpg" alt="فريق كاتو أثناء تنفيذ أعمال الصيانة"><div class="float"><b>كاتو</b><span>كفاءة · إدارة · تنفيذ · وقت</span></div></div><div class="rv d1"><span class="eyebrow">نظام تشغيل متكامل</span><h2>نظام تشغيل متكامل يقلل توقف الإنتاج ويرفع كفاءة شغلك</h2><ol class="steps-v">${[['ك', 'كفاءة', 'أعلى أداء لمعداتك وخطوط إنتاجك'],['ا', 'إدارة', 'إدارة وتشغيل منظم للمرافق داخل موقعك'],['ت', 'تنفيذ', 'فريق متخصص بأعلى معايير الجودة والسلامة'],['و', 'وقت', 'التزام بالمواعيد واستجابة خلال ساعات']].map(([k, t, d]) => `<li><span class="k">${k}</span><div><h4>${t}</h4><p>${d}</p></div></li>`).join('')}</ol></div></div></section>`,

about: () => `<section class="section" id="about"><div class="container about"><div class="imgs rv"><img class="i1" loading="lazy" src="${IMG}p-electrical.jpg" alt="مهندس كاتو في موقع عمل"><img class="i2" loading="lazy" src="${IMG}p-ac.jpg" alt="صيانة صناعية"><div class="exp"><b>5+</b><small>سنوات خبرة ميدانية</small></div></div><div class="rv d1"><span class="eyebrow">من نحن</span><h2>كاتو مش مجرد صيانة — ده نظام تشغيل</h2><p class="lead">كاتو مركز خدمة متخصص في الصيانة والمقاولات للمصانع والشركات. نقدم إدارة وتشغيل وصيانة متكاملة للمرافق داخل المواقع الصناعية بعقلية وقائية وفريق عمل منظم.</p><p>هدفنا ليس إصلاح العطل فقط، بل منعه من الأساس. من خلال خطة صيانة واضحة، وتنفيذ منظم، وتقارير فنية تساعد الإدارة على اتخاذ القرار الصحيح في الوقت المناسب.</p><ul class="checks">${['الجودة قبل الكمية', 'الاعتمادية في المواعيد', 'السلامة فوق الإنتاج', 'التطوير المستمر', 'الالتزام بالعقد'].map(x => `<li>${ic('cc')}${x}</li>`).join('')}</ul>${PAGE === 'about' ? `<a class="btn btn-navy" href="contact.html">احجز معاينة مجانية</a>` : `<a class="btn btn-navy" href="about.html">تعرف علينا أكثر</a>`}</div></div></section>`,

why: () => `<section class="section dark" id="why"><div class="container why"><div class="sticky rv"><span class="eyebrow">لماذا KATO</span><h2>ما الذي يميزنا في سوق الصيانة الصناعية؟</h2><p class="lead" style="margin-top:14px">لا نقدم خدمة صيانة فقط — نقدم نظام تشغيل كامل يهدف لتقليل توقفات الإنتاج ورفع كفاءة الموقع.</p><img loading="lazy" src="${IMG}p-install.jpg" alt="فنيو كاتو المعتمدون"></div><ol class="why-list">${WHY.map(([t, d], i) => `<li class="rv"><b>0${i + 1}</b><div><h4>${t}</h4><p>${d}</p></div></li>`).join('')}</ol></div></section>`,

industries: () => `<section class="section" id="industries"><div class="container">${head('القطاعات', 'نخدم قطاعات صناعية متنوعة بموثوقية', 'فريقنا يفهم متطلبات كل قطاع ويقدم حلول صيانة وتشغيل مصممة للبيئة الخاصة بكل مصنع. من خطوط الإنتاج إلى المرافق اللوجستية.')}<div class="ind-grid">${IND.map(([t, d, im], i) => `<article class="ind rv d${i % 4}" tabindex="0"><img loading="lazy" src="${IMG + im}.jpg" alt=""><span class="n">0${i + 1}</span><div class="in"><h3>${t}</h3><p>${d}</p></div></article>`).join('')}</div></div></section>`,

projects: el => { const lim = +el.dataset.limit || 99, list = PRJ.slice(0, lim); return `<section class="section soft" id="projects"><div class="container">${head('مشاريعنا', 'مشاريع نفخر بتنفيذها', 'نماذج مختارة من أعمالنا في قطاعات مختلفة. اضغط على أي مشروع لعرض تفاصيله.')}<div class="filters" role="group" aria-label="تصفية المشاريع"><button class="on" data-f="all">الكل</button>${Object.entries(CATS).map(([k, v]) => `<button data-f="${k}">${v}</button>`).join('')}</div><div class="masonry" id="pgrid">${list.map((p, i) => `<button class="pj ${p.sz}" data-c="${p.c}" data-i="${PRJ.indexOf(p)}" aria-label="تفاصيل: ${p.t}"><img loading="lazy" src="${IMG + p.img}.jpg" alt="${p.t}"><span class="pl">${ic('plus')}</span><span class="ov"><span class="tp">${CATS[p.c]}${p.sec ? ' · ' + p.sec : ''}</span><h3>${p.t}</h3>${p.loc ? `<small>${p.loc}</small>` : ''}</span></button>`).join('')}</div>${lim < 99 ? `<div style="text-align:center;margin-top:20px"><a class="btn btn-navy" href="projects.html">كل المشاريع</a></div>` : ''}</div></section>`; },

process: () => `<section class="section" id="process"><div class="container">${head('طريقة العمل', 'من المعاينة إلى التقارير الدورية', 'منهجية واضحة ومختبرة في كل مشروع. كل خطوة موثقة، وكل مرحلة لها مخرجات محددة.', 'center')}<ol class="proc">${STEPS.map(([t, d], i) => `<li class="pstep rv d${i % 3}"><span class="c">0${i + 1}</span><div><h4>${t}</h4><p>${d}</p></div></li>`).join('')}</ol></div></section>`,

safety: () => `<section class="section dark"><div class="container safety"><div class="rv"><span class="eyebrow">السلامة والجودة</span><h2>السلامة ليست خيارًا</h2><p class="lead" style="margin-top:12px">نضع معايير السلامة والجودة في صميم عمليات التصميم والتنفيذ والصيانة لضمان حلول موثوقة وآمنة.</p><ul class="slist">${['السلامة فوق الإنتاج في كل موقع نعمل به', 'الجودة قبل الكمية في كل بند تنفيذ', 'تقارير موثقة قبل وبعد كل عمل صيانة'].map(x => `<li>${ic('shield')}<span>${x}</span></li>`).join('')}</ul><p style="margin-bottom:12px;font-weight:600">نلتزم بالمعايير الصناعية المعتمدة</p><div class="badges">${STD.map(x => `<span>${x}</span>`).join('')}</div></div><div class="img rv d1"><img loading="lazy" src="${IMG}p-safety.jpg" alt="معايير السلامة في المواقع الصناعية"></div></div></section>`,

vision: () => `<section class="section"><div class="container"><div class="vm rv"><div class="v"><span class="ic">${ic('eye')}</span><h3>رؤيتنا</h3><p>أن نكون شريك التشغيل الأول للمصانع في منطقة القناة وجمهورية مصر العربية.</p></div><div class="m"><span class="ic">${ic('target')}</span><h3>رسالتنا</h3><p>تقليل خسائر التوقف ورفع استقرار التشغيل من خلال صيانة وقائية حقيقية ونظام تنفيذ منظم.</p></div></div></div></section>`,

testimonials: () => `<section class="section soft"><div class="container">${head('آراء العملاء', 'ماذا يقول عملاؤنا؟', 'نتائجنا وثقتنا في التعامل تتحدث من خلال العملاء الذين وثقوا بنا.', 'center')}<div class="tes-grid">${TES.map(([q, n, r], i) => `<figure class="tes rv d${i}"><div class="stars" aria-label="تقييم 5 من 5">★★★★★</div><blockquote><p>${q}</p></blockquote><figcaption class="who"><span class="av">${n.split(' ')[1][0]}</span><span><b>${n}</b><small>${r}</small></span></figcaption></figure>`).join('')}</div></div></section>`,

faq: () => `<section class="section" id="faq"><div class="container faq-wrap"><div class="rv"><span class="eyebrow">الأسئلة الشائعة</span><h2>كل ما تريد معرفته قبل البدء</h2><p class="lead" style="margin:12px 0 24px">لم تجد إجابتك؟ فريقنا متاح لمساعدتك.</p><a class="btn btn-navy" href="contact.html">تواصل معنا</a></div><div class="faq rv d1">${FAQ.map(([q, a], i) => `<details${i == 0 ? ' open' : ''}><summary>${q}${ic('plus')}</summary><div class="ans">${a}</div></details>`).join('')}</div></div></section>`,

cta: () => `<section class="section cta-band"><div class="container rv"><h2>هل مصنعك يحتاج إلى شريك تشغيل موثوق؟</h2><p class="lead">احجز معاينة مجانية لموقعك، وفريقنا هيتواصل معاك خلال 24 ساعة لتحديد الموعد.</p><div class="cta"><a class="btn btn-gold" href="contact.html">احجز معاينة مجانية</a><a class="btn btn-ghost" href="${C.wa}" target="_blank" rel="noopener">${ic('wa')} تواصل عبر واتساب</a></div></div></section>`,

servicesDetail: () => `<section class="section"><div class="container">${SVC.map((s, i) => `<article class="drow" id="s${i + 1}"><div class="dimg rv"><span class="big">0${i + 1}</span><img loading="lazy" src="${IMG + s.img}.jpg" alt="${s.t}"></div><div class="rv d1"><span class="eyebrow">خدمة 0${i + 1}</span><h2>${s.t}</h2><p class="lead" style="margin:10px 0">${s.d}</p><div class="dcols">${s.g.map(([h, l]) => `<div><h4>${h}</h4><ul>${l.map(x => `<li>${ic('check')}${x}</li>`).join('')}</ul></div>`).join('')}</div><div class="tags">${s.sec.map(x => `<span>${x}</span>`).join('')}</div><a class="btn btn-navy" href="contact.html?service=${encodeURIComponent(s.t)}">احجز معاينة لهذه الخدمة</a></div></article>`).join('')}</div></section>`,

plans: () => `<section class="section soft" id="plans"><div class="container">${head('أنظمة التعاقد', 'اختر النظام المناسب لحجم موقعك', 'ثلاثة أنظمة مرنة، من زيارات تفقدية بسيطة إلى تشغيل متكامل. التفاصيل النهائية تُحدد بعد المعاينة الفنية.', 'center')}<div class="plans">${PLANS.map((p, i) => `<article class="plan rv d${i}${i == 1 ? ' rec' : ''}"><span class="bd">${p[0]}</span><h3>${p[1]}</h3><p>${p[2]}</p><table>${p[3].map((v, k) => `<tr><td>${ROWS[k]}</td><td>${v}</td></tr>`).join('')}</table><a class="btn ${i == 1 ? 'btn-gold' : 'btn-line'}" href="contact.html">${p[4]}</a><small>${p[5]}</small></article>`).join('')}</div></div></section>`,

timeline: () => `<section class="section"><div class="container">${head('رحلتنا', 'رحلتنا حتى الآن', '+500 موقع، +5 سنوات خبرة ميدانية', 'center')}<ol class="tl">${TL.map(([y, t, d]) => `<li class="rv"><b>${y}</b><div><h4>${t}</h4><p>${d}</p></div></li>`).join('')}</ol></div></section>`,

kpis: () => `<section class="section soft"><div class="container">${head('مؤشرات الأداء', 'نتائجنا تتحدث عنا', 'نتائج مجمعة من جميع العقود النشطة خلال آخر 12 شهرًا', 'center')}<div class="grid4">${KPI.map(([t, v, tr, i], k) => `<div class="card rv d${k % 4}"><span class="ic">${ic(i)}</span><div class="big">${v}</div><h4 style="font-size:1rem">${t}</h4><span class="tr">${tr}</span></div>`).join('')}</div></div></section>`,

reports: () => `<section class="section"><div class="container">${head('التقارير والمتابعة', 'تقارير تساعد الإدارة على اتخاذ القرار', 'نقدّم تقارير دورية مفصلة عن حالة الموقع، المخاطر، التوصيات، وخطط التحسين.', 'center')}<div class="grid4">${REP.map(([t, d, i], k) => `<div class="card rv d${k % 4}"><span class="ic">${ic(i)}</span><h3>${t}</h3><p>${d}</p></div>`).join('')}</div></div></section>`,

contact: el => `<section class="section" id="contact"><div class="container"><div class="ct"><div class="rv"><span class="eyebrow">تواصل معنا</span><h2>تحدث مع فريقنا</h2><p class="lead" style="margin:12px 0 20px">متاحون على مدار الساعة للطوارئ. للحجز والاستفسار استخدم القنوات التالية.</p><ul class="cinfo">${[['phone', 'الهاتف', C.phone + ' — ' + C.phone2, 'tel:' + C.phone], ['wa', 'واتساب مباشر', 'wa.me/201028644675', C.wa], ['mail', 'البريد الإلكتروني', C.mail, 'mailto:' + C.mail], ['fb', 'فيسبوك', 'صفحة كاتو على فيسبوك', C.fb], ['pin', 'الموقع', C.addr, ''], ['clock', 'أوقات العمل', 'متاحون للطوارئ 24/7', '']].map(([i, t, v, h]) => `<li><span class="ic">${ic(i)}</span><div><h4>${t}</h4>${h ? `<a href="${h}"${h.startsWith('http') ? ' target="_blank" rel="noopener"' : ''}>${v}</a>` : `<span>${v}</span>`}</div></li>`).join('')}</ul></div><form class="form rv d1" id="cf" novalidate><h3>احجز معاينة مجانية</h3><p style="color:var(--mut)">سيب بياناتك وهنتواصل معاك خلال 24 ساعة.</p><div class="frow"><div class="field"><label for="f-name">الاسم</label><input id="f-name" autocomplete="name"><em></em></div><div class="field"><label for="f-phone">رقم الجوال</label><input id="f-phone" type="tel" autocomplete="tel"><em></em></div></div><div class="field"><label for="f-mail">البريد الإلكتروني (اختياري)</label><input id="f-mail" type="email" autocomplete="email"><em></em></div><div class="field"><label for="f-svc">نوع الخدمة</label><select id="f-svc"><option value="">اختر الخدمة...</option>${SVC.map(s => `<option>${s.t}</option>`).join('')}<option>عقد صيانة شهرية</option><option>تشغيل كامل</option><option>أخرى</option></select><em></em></div><div class="field"><label for="f-msg">رسالتك</label><textarea id="f-msg" rows="4"></textarea></div><button class="btn btn-gold" type="submit">إرسال الطلب</button><div class="ok" id="ok" hidden role="status">تم تجهيز طلبك — أكمل الإرسال عبر واتساب وسيتواصل معك فريقنا خلال 24 ساعة.</div></form></div>${el.dataset.map ? `<div class="map rv"><iframe title="موقع كاتو – السويس" loading="lazy" src="https://www.google.com/maps?q=El+Salam+1,+Suez,+Egypt&output=embed"></iframe></div>` : ''}</div></section>`
};

/* ---------- shared header / footer / floating ---------- */
const NAV = [['home', 'index.html', 'الرئيسية'], ['about', 'about.html', 'من نحن'], ['services', 'services.html', 'خدماتنا'], ['projects', 'projects.html', 'مشاريعنا'], ['why', 'index.html#why', 'لماذا نحن'], ['faq', 'index.html#faq', 'الأسئلة الشائعة'], ['contact', 'contact.html', 'تواصل معنا']];
const logo = `<a class="logo" href="index.html" aria-label="KATO – الرئيسية"><span class="mk">${ic('zap')}</span><span><b>KATO</b><small>كفاءة · إدارة · تنفيذ · وقت</small></span></a>`;
$('#site-header').outerHTML = `<div class="topstrip"><div class="container"><div><span>${ic('clock')} متاحون للطوارئ 24/7</span><span>${ic('pin')} السويس – مصر</span></div><div><span>${ic('phone')} <a href="tel:${C.phone}">${C.phone}</a></span></div></div></div><header class="header" id="hd"><div class="container">${logo}<nav class="nav" id="nav" aria-label="القائمة الرئيسية">${NAV.map(([k, h, t]) => `<a href="${h}"${k === PAGE ? ' class="active" aria-current="page"' : ''}>${t}</a>`).join('')}</nav><div class="hact"><a class="wa-btn" href="${C.wa}" target="_blank" rel="noopener" aria-label="واتساب">${ic('wa')}</a><a class="btn btn-navy" href="contact.html">احجز معاينة مجانية</a><button class="burger" id="bg" aria-label="فتح القائمة" aria-expanded="false">☰</button></div></div></header>`;
$('#site-footer').outerHTML = `<footer class="footer"><div class="container"><div class="fgrid"><div>${logo}<p>مركز صيانة ومقاولات متكامل للمصانع والشركات في مصر. نقلل توقف الإنتاج ونرفع كفاءة تشغيلك من خلال فرق متخصصة وتقارير فنية موثوقة.</p><div class="soc"><a href="${C.fb}" target="_blank" rel="noopener" aria-label="فيسبوك">${ic('fb')}</a><a href="${C.wa}" target="_blank" rel="noopener" aria-label="واتساب">${ic('wa')}</a></div></div><div><h4>روابط سريعة</h4>${NAV.slice(0, 4).map(([, h, t]) => `<a href="${h}">${t}</a>`).join('')}<a href="contact.html">تواصل معنا</a></div><div><h4>الخدمات</h4>${SVC.map((s, i) => `<a href="services.html#s${i + 1}">${s.t}</a>`).join('')}</div><div><h4>تواصل معنا</h4><p>${C.phone} – ${C.phone2}</p><p>${C.mail}</p><p>${C.addr}</p></div></div><div class="fbot"><span>© 2026 KATO. جميع الحقوق محفوظة.</span><span>كفاءة · إدارة · تنفيذ · وقت</span></div></div></footer><div class="fab"><button class="up" id="up" aria-label="العودة للأعلى">${ic('up')}</button><a class="wa" href="${C.wa}" target="_blank" rel="noopener" aria-label="تواصل عبر واتساب">${ic('wa')}</a></div><div class="modal" id="modal" hidden role="dialog" aria-modal="true" aria-label="تفاصيل المشروع"><div class="mbox"><button class="x" aria-label="إغلاق">×</button><img alt=""><div class="mb"></div></div></div>`;

/* ---------- render placeholders ---------- */
$$('[data-render]').forEach(el => { const f = R[el.dataset.render]; if (f) el.outerHTML = f(el); });

$$('[data-ic]').forEach(e => e.insertAdjacentHTML('afterbegin', ic(e.dataset.ic)));

/* ---------- behaviours ---------- */
const hd = $('#hd'), up = $('#up');
const onScroll = () => { hd.classList.toggle('scrolled', scrollY > 30); up.classList.toggle('show', scrollY > 600); };
addEventListener('scroll', onScroll, {passive: true}); onScroll();
const nav = $('#nav'), bg = $('#bg');
bg.onclick = () => { const o = nav.classList.toggle('open'); bg.setAttribute('aria-expanded', o); bg.textContent = o ? '✕' : '☰'; };
nav.onclick = e => e.target.closest('a') && nav.classList.remove('open');
up.onclick = () => scrollTo({top: 0, behavior: 'smooth'});
// reveal + counters
const io = new IntersectionObserver(es => es.forEach(e => { if (!e.isIntersecting) return; e.target.classList.add('in'); const c = $('[data-count]', e.target); if (c) count(c); io.unobserve(e.target); }), {threshold: .12});
$$('.rv').forEach(el => io.observe(el));
function count(el) { const to = +el.dataset.count, t0 = performance.now(), d = 1400; (function f(t) { const p = Math.max(0, Math.min((t - t0) / d, 1)); el.textContent = Math.round(to * (1 - Math.pow(1 - p, 3))); p < 1 && requestAnimationFrame(f); })(t0); }
// projects filter + modal
const grid = $('#pgrid'), modal = $('#modal');
$$('.filters button').forEach(b => b.onclick = () => { $$('.filters button').forEach(x => x.classList.toggle('on', x === b)); $$('.pj', grid).forEach(p => p.hidden = b.dataset.f !== 'all' && p.dataset.c !== b.dataset.f); });
let last;
grid && grid.addEventListener('click', e => { const b = e.target.closest('.pj'); if (!b) return; const p = PRJ[b.dataset.i]; last = b;
 $('img', modal).src = IMG + p.img + '.jpg'; $('img', modal).alt = p.t;
 $('.mb', modal).innerHTML = `<span class="eyebrow">${CATS[p.c]}</span><h3 style="font-size:1.5rem">${p.t}</h3>${p.loc ? `<dl><dt>القطاع</dt><dd>${p.sec}</dd><dt>الموقع</dt><dd>${p.loc}</dd></dl>` : ''}${p.d ? `<p style="color:var(--mut);margin-top:10px">${p.d}</p>` : ''}${p.r ? `<div class="res-pill"><b>${p.r}</b><span>${p.rl}</span></div>` : ''}<div style="margin-top:14px"><a class="btn btn-gold" href="contact.html">اطلب مشروعًا مماثلًا</a></div>`;
 modal.hidden = false; $('.x', modal).focus(); });
const close = () => { modal.hidden = true; last && last.focus(); };
modal.onclick = e => (e.target === modal || e.target.closest('.x')) && close();
addEventListener('keydown', e => e.key === 'Escape' && !modal.hidden && close());
// FAQ: one open at a time
const ds = $$('.faq details'); ds.forEach(d => d.addEventListener('toggle', () => d.open && ds.forEach(o => o !== d && (o.open = false))));
// contact form → WhatsApp
const cf = $('#cf');
if (cf) {
 const q = new URLSearchParams(location.search).get('service'); q && ($('#f-svc').value = q);
 cf.onsubmit = e => { e.preventDefault(); const v = id => $('#' + id).value.trim(); let ok = true;
  [['f-name', v('f-name').length < 2, 'من فضلك ادخل اسمك'], ['f-phone', !/^[0-9+\s-]{8,15}$/.test(v('f-phone')), 'رقم جوال غير صالح'], ['f-svc', !v('f-svc'), 'من فضلك اختر الخدمة']].forEach(([id, bad, m]) => { const f = $('#' + id).closest('.field'); f.classList.toggle('err', bad); $('em', f).textContent = bad ? m : ''; if (bad) ok = false; });
  if (v('f-mail') && !/^\S+@\S+\.\S+$/.test(v('f-mail'))) { ok = false; $('#f-mail').closest('.field').classList.add('err'); $('#f-mail').nextElementSibling.textContent = 'بريد إلكتروني غير صالح'; }
  if (!ok) return;
  const msg = `طلب معاينة – KATO\nالاسم: ${v('f-name')}\nالجوال: ${v('f-phone')}\nالبريد: ${v('f-mail')}\nالخدمة: ${v('f-svc')}\nالرسالة:\n${v('f-msg')}`;
  $('#ok').hidden = false; open(C.wa + '?text=' + encodeURIComponent(msg), '_blank', 'noopener'); cf.reset(); };
}
})();
